"""User-facing handle and artifact writers for emitted HLS designs."""

from __future__ import annotations

import hashlib
import json
import math
import os
import re
from pathlib import Path

from ..._version import __version__
from ...errors import LaunchError

__all__ = ["HLSDesign"]


class HLSDesign:
    """Handle to an emitted HLS C++ design."""

    _DECLARATIONS = re.compile(
        r"^// SAR_DSL_DECLARATIONS_BEGIN\n(?P<body>.*?)"
        r"^// SAR_DSL_DECLARATIONS_END\n", re.M | re.S)
    _TABLES = re.compile(
        r"^// SAR_DSL_TABLES_BEGIN\n(?P<body>.*?)"
        r"^// SAR_DSL_TABLES_END\n", re.M | re.S)

    def __init__(self, cpp_path: str, name: str, metadata=None, config=None):
        self.cpp_path = str(cpp_path)
        self.name = name
        self.config = config
        self._metadata = metadata
        try:
            self._source = Path(self.cpp_path).read_text()
        except OSError as exc:
            raise LaunchError(
                f"HLS artifact for {self.name!r} is unavailable at "
                f"{self.cpp_path}; recompile the kernel") from exc

    def source(self) -> str:
        return self._source

    @property
    def tables_name(self) -> str:
        """Basename of the ROM header, when the design has constant tables."""
        return f"{self.name}_tables"

    def has_tables(self) -> bool:
        """Whether the design carries lifted constant (ROM) tables."""
        return self._TABLES.search(self.source()) is not None

    def tables_source(self) -> str:
        """ROM tables as their own header.

        The twiddle, axis and window tables are pure data and routinely
        outweigh the logic; keeping them in `<top>_tables.h` leaves the
        implementation file readable while Vitis still sees file-scope
        `static const` arrays it can map to ROM.
        """
        match = self._TABLES.search(self.source())
        if match is None:
            raise LaunchError(
                f"HLS artifact for {self.name!r} has no constant tables")
        guard = re.sub(r"[^A-Za-z0-9]", "_", self.tables_name).upper()
        return ("//===- SAR-DSL generated Vitis HLS constant tables "
                "--------------*- C++ -*-===//\n"
                "//\n"
                "// Generated by SAR-DSL HLS artifact generation.\n"
                "// Regenerate this file instead of editing it.\n"
                "//\n"
                "//===------------------------------------------------------"
                "----------------===//\n\n"
                f"#ifndef SAR_DSL_{guard}_H\n"
                f"#define SAR_DSL_{guard}_H\n\n"
                "#include <cstdint>\n\n" + match.group("body").strip() +
                f"\n\n#endif // SAR_DSL_{guard}_H\n")

    def header_source(self) -> str:
        """Declarations used by packaged synthesis and simulation projects."""
        match = self._DECLARATIONS.search(self.source())
        if match is None:
            raise LaunchError(
                f"HLS artifact for {self.name!r} has no declaration block")
        top = re.search(rf"^void {re.escape(self.name)}\(\n.*?\n\) \{{",
                        self.source(), re.M | re.S)
        if top is None:
            raise LaunchError(
                f"HLS artifact for {self.name!r} has no top definition")
        top_declaration = top.group(0)[:-2] + ";"
        declarations = top_declaration
        helpers = match.group("body").strip()
        if helpers:
            declarations += "\n\n" + helpers
        includes = ["#include <cstdint>"]
        for token, header in (("ap_int<", "ap_int.h"),
                              ("ap_uint<", "ap_int.h"), ("hls::stream<",
                                                         "hls_stream.h"),
                              ("hls::vector<", "hls_vector.h")):
            include = f"#include <{header}>"
            if token in declarations and include not in includes:
                includes.append(include)
        guard = re.sub(r"[^A-Za-z0-9]", "_", self.name).upper()
        return (
            "//===- SAR-DSL generated Vitis HLS declarations "
            "-----------------*- C++ -*-===//\n"
            "//\n"
            "// Generated by SAR-DSL HLS artifact generation.\n"
            "// Regenerate this file instead of editing it.\n"
            "//\n"
            "//===----------------------------------------------------------------------===//\n\n"
            f"#ifndef SAR_DSL_{guard}_H\n"
            f"#define SAR_DSL_{guard}_H\n\n" + "\n".join(includes) + "\n\n" +
            declarations + "\n\n"
            f"#endif // SAR_DSL_{guard}_H\n")

    @staticmethod
    def _marked_section_start(source: str, marker_start: int) -> int:
        """Start of the titled section immediately preceding a marker."""
        closing_rule = source.rfind("//===", 0, marker_start)
        if closing_rule < 0:
            return marker_start
        opening_rule = source.rfind("//===", 0, closing_rule)
        return opening_rule if opening_rule >= 0 else closing_rule

    @classmethod
    def _remove_marked_section(cls, source: str, match) -> str:
        """Remove a marked block and its title, leaving one blank line."""
        start = cls._marked_section_start(source, match.start())
        return source[:start].rstrip() + "\n\n" + source[match.end():].lstrip()

    def _packaged_source(self) -> str:
        match = self._DECLARATIONS.search(self.source())
        if match is None:
            raise LaunchError(
                f"HLS artifact for {self.name!r} has no declaration block")
        source = self._remove_marked_section(self.source(), match)
        headers = [f'#include "{self.name}.h"']
        tables = self._TABLES.search(source)
        if tables is not None:
            source = self._remove_marked_section(source, tables)
            headers.append(f'#include "{self.tables_name}.h"')
        includes = list(re.finditer(r"^#include <[^>]+>$", source, re.M))
        if not includes:
            raise LaunchError(
                f"HLS artifact for {self.name!r} has no include section")
        insert = includes[-1].end()
        return (source[:insert] + "\n" + "\n".join(headers) + source[insert:])

    def _write_sources(self, output_dir: Path) -> None:
        (output_dir / f"{self.name}.h").write_text(self.header_source())
        if self.has_tables():
            (output_dir / f"{self.tables_name}.h").write_text(
                self.tables_source())
        (output_dir / f"{self.name}.cpp").write_text(self._packaged_source())

    def _interface_schema(self) -> list:
        encoded = re.findall(r"^// SAR_DSL_INTERFACE: (?P<port>\{.*\})$",
                             self.source(), re.M)
        if encoded:
            try:
                schema = [json.loads(port) for port in encoded]
            except json.JSONDecodeError as exc:
                raise LaunchError(
                    f"HLS artifact for {self.name!r} has malformed interface "
                    f"metadata: {exc}") from exc
            if any(not isinstance(port, dict) for port in schema):
                raise LaunchError(
                    f"HLS artifact for {self.name!r} has invalid interface "
                    "metadata")
            return schema
        raise LaunchError(
            f"HLS artifact for {self.name!r} has no interface metadata")

    def interface_schema(self) -> list:
        """Physical top-level ports in declaration order."""
        return [dict(port) for port in self._interface_schema()]

    def _write_manifest(self, output_dir: Path) -> Path:
        config = self.config.as_dict() if self.config is not None else {}
        provenance = (self.config.provenance
                      if self.config is not None else {})
        metadata = self._metadata
        performance_plan = metadata.extra.get("hls_performance_plan")
        if performance_plan is None:
            plan_schema = None
        else:
            # The values are split by how the compiler arrived at them: a
            # `tuned` key was modelled against this kernel and these budgets
            # and is where the latency/area trade-off was made, while a
            # `fixed` key is the same for every design. Reading a plan
            # without that split invites treating a constant as a decision.
            from .autotune import FIXED_OPTIONS, TUNED_OPTIONS
            values = performance_plan.values
            plan_schema = {
                "clock_ns": performance_plan.clock_ns,
                "timing_budget_ns": performance_plan.timing_budget_ns,
                "on_chip_bytes": performance_plan.on_chip_bytes,
                "memory_accesses": performance_plan.memory_accesses,
                "operation_count": performance_plan.operation_count,
                "values": values,
                "tuned": {
                    key: values[key]
                    for key in TUNED_OPTIONS if key in values
                },
                "fixed": {
                    key: values[key]
                    for key in FIXED_OPTIONS if key in values
                },
            }

        def tensor_schema(tensor_type):
            return {
                "shape": list(tensor_type.shape),
                "dtype": tensor_type.dtype.name,
                "mlir": tensor_type.mlir,
            }

        path = output_dir / "design_manifest.json"
        path.write_text(
            json.dumps(
                {
                    "schema_version":
                    2,
                    "top":
                    self.name,
                    "source_sha256":
                    hashlib.sha256(
                        self._packaged_source().encode()).hexdigest(),
                    "header_sha256":
                    hashlib.sha256(self.header_source().encode()).hexdigest(),
                    "generator": {
                        "name": "sar-dsl",
                        "version": __version__,
                        "backend": "hls",
                    },
                    "kernel": {
                        "name":
                        metadata.name,
                        "parameters":
                        list(metadata.param_names or []),
                        "arguments":
                        [tensor_schema(t) for t in metadata.arg_types],
                        "results":
                        [tensor_schema(t) for t in metadata.result_types],
                    },
                    "requested_options":
                    dict(metadata.extra.get("hls_requested_options", {})),
                    "interfaces":
                    self._interface_schema(),
                    "config":
                    config,
                    "config_provenance":
                    provenance,
                    "optimization_plan":
                    plan_schema,
                },
                indent=2,
                sort_keys=True) + "\n")
        return path

    def write_testbench(self,
                        inputs,
                        expected,
                        output_dir=None,
                        rtol: float = 1e-4,
                        atol: float = 1e-5,
                        max_bytes: int | None = None) -> Path:
        """Writes a self-contained HLS validation package.

        `max_bytes` bounds the static arrays declared by the generated
        harness. Null uses `SAR_DSL_HLS_TESTBENCH_MAX_BYTES` (1 GiB by
        default); zero explicitly disables the guard for a caller that chose
        a production-scale simulation.
        """
        from . import compiler

        tolerances = {}
        for name, value in (("rtol", rtol), ("atol", atol)):
            try:
                value = float(value)
            except (TypeError, ValueError):
                raise LaunchError(
                    f"{name} must be a finite non-negative number") from None
            if not math.isfinite(value) or value < 0:
                raise LaunchError(
                    f"{name} must be a finite non-negative number")
            tolerances[name] = value

        meta = self._metadata
        in_ports = compiler._split_planes("in", meta.arg_types)
        out_ports = compiler._split_planes("out", meta.result_types)
        physical_ports = None
        if self.config is not None and self.config.interface in ("axi",
                                                                 "stream"):
            physical_ports = self._interface_schema()
            if (len(physical_ports) < len(in_ports) + len(out_ports)):
                raise LaunchError(
                    "cannot recover the generated AXI top signature")
        schema = physical_ports or self._interface_schema()
        static_bytes = sum(
            math.prod(port["physical_shape"]) * port["data_bits"] // 8
            for port in schema)
        static_bytes += max((math.prod(port[1]) * 8 for port in out_ports),
                            default=0)
        if max_bytes is None:
            raw_limit = os.environ.get("SAR_DSL_HLS_TESTBENCH_MAX_BYTES",
                                       str(1 << 30))
            try:
                limit = int(raw_limit)
            except ValueError:
                raise LaunchError(
                    "SAR_DSL_HLS_TESTBENCH_MAX_BYTES must be an integer") \
                    from None
        elif isinstance(max_bytes, bool) or not isinstance(max_bytes, int):
            raise LaunchError("max_bytes must be a non-negative integer")
        else:
            limit = max_bytes
        if limit < 0:
            raise LaunchError("max_bytes must be a non-negative integer")
        if limit and static_bytes > limit:
            raise LaunchError(
                f"generated testbench needs about {static_bytes / 2**30:.2f} "
                f"GiB of static arrays, above the configured "
                f"{limit / 2**30:.2f} GiB limit")
        arrays = (
            list(compiler._plane_data(inputs, meta.arg_types)) +
            list(compiler._golden_plane_data(expected, meta.result_types)))

        out = Path(
            output_dir if output_dir is not None else Path("hls_project") /
            self.name)
        data_dir = out / f"{self.name}_tb_data"
        data_dir.mkdir(parents=True, exist_ok=True)
        for (port, _, _), values in zip(in_ports + out_ports, arrays):
            values.reshape(-1).tofile(data_dir / f"{port}.bin")

        self._write_sources(out)
        testbench = out / f"{self.name}_tb.cpp"
        testbench.write_text(
            compiler._testbench_source(self.name, in_ports, out_ports,
                                       tolerances["rtol"], tolerances["atol"],
                                       physical_ports))
        part, clock = compiler._part_and_clock(self.config)
        (out / f"{self.name}_hls_csim.tcl").write_text(
            compiler._hls_csim_script(self.name, part, clock))
        portable = out / f"{self.name}_portable_cpp_sim.sh"
        portable.write_text(compiler._portable_cpp_sim_script(self.name))
        portable.chmod(0o755)
        (out / f"{self.name}_csynth.tcl").write_text(
            compiler._csynth_script(self.name, part, clock, self.config))
        (out / f"{self.name}_cosim.tcl").write_text(
            compiler._cosim_script(self.name, part, clock, self.config))
        compiler._write_header_stubs(out / "stubs")
        self._write_manifest(out)
        return testbench

    def write_synthesis_script(self, output_dir=None) -> Path:
        """Writes the design and its Vitis HLS synthesis script."""
        from . import compiler

        out = Path(
            output_dir if output_dir is not None else Path("hls_project") /
            self.name)
        out.mkdir(parents=True, exist_ok=True)
        self._write_sources(out)
        self._write_manifest(out)
        part, clock = compiler._part_and_clock(self.config)
        script = out / f"{self.name}_csynth.tcl"
        script.write_text(
            compiler._csynth_script(self.name, part, clock, self.config))
        return script

    def __call__(self, *args, **kwargs):
        raise LaunchError(
            "HLS designs are emitted as C++ for Vitis HLS synthesis and "
            f"cannot be executed directly; see {self.cpp_path}")

    def __repr__(self) -> str:
        return f"HLSDesign({self.name} @ {self.cpp_path})"
