#!/usr/bin/env python3
"""Generate deterministic constant ROMs used by synthesizable FP32 kernels."""

from __future__ import annotations

import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "generated" / "wka_luts.h"
SIZES = (256, 16384)
C0 = 299792458.0
FC = 1269999750.06
FS = 32000000.0
PRF = 2155.172
VR = 7072.0
R0 = 843013.994
KR = -1.037e12
PULSE_LEN = 27.0e-6


def emit_array(handle,
               name: str,
               values: list[float],
               columns: int = 6) -> None:
    handle.write(f"static const float {name}[{len(values)}] = {{\n")
    for start in range(0, len(values), columns):
        chunk = values[start:start + columns]
        handle.write("    " + ", ".join(f"{value:.9e}f"
                                        for value in chunk) + ",\n")
    handle.write("};\n\n")


def band_window(n: int, fraction: float) -> list[float]:
    width = max(4, min(n, int(round(n * fraction))))
    start = (n - width) // 2
    values = [0.0] * n
    for index in range(width):
        values[start + index] = 0.5 - 0.5 * math.cos(2.0 * math.pi * index /
                                                     (width - 1))
    return values


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8") as handle:
        handle.write(
            "//===- wka_luts.h - Generated omega-K lookup tables "
            "-----------------===//\n"
            "//\n"
            "// Part of the SAR-DSL Project. Licensed under the MIT License.\n"
            "// Generated by scripts/generate_luts.py; do not edit.\n"
            "//\n"
            "//===----------------------------------------------------------"
            "--------------------===//\n\n")
        handle.write(
            "#ifndef WKA_GENERATED_LUTS_H\n#define WKA_GENERATED_LUTS_H\n\n")
        for index, n in enumerate(SIZES):
            handle.write(("#if" if index == 0 else "#elif") +
                         f" WKA_N == {n}\n\n")
            twiddle_cos = [
                math.cos(-2.0 * math.pi * k / n) for k in range(n // 2)
            ]
            twiddle_sin = [
                math.sin(-2.0 * math.pi * k / n) for k in range(n // 2)
            ]
            range_fraction = min(1.0, abs(KR) * PULSE_LEN / FS)
            doppler_span = 2.0 * VR**2 * (n / PRF) / ((C0 / FC) * R0)
            azimuth_fraction = min(1.0, doppler_span / PRF)
            emit_array(handle, "WKA_TWIDDLE_COS_ROM", twiddle_cos)
            emit_array(handle, "WKA_TWIDDLE_SIN_ROM", twiddle_sin)
            emit_array(handle, "WKA_RANGE_WINDOW_ROM",
                       band_window(n, range_fraction))
            emit_array(handle, "WKA_AZIMUTH_WINDOW_ROM",
                       band_window(n, azimuth_fraction))
        handle.write(
            "#else\n#error Unsupported WKA_N for generated LUTs\n#endif\n\n")

        handle.write("#endif\n")
    print(OUTPUT)


if __name__ == "__main__":
    main()
