"""The four complete imaging chains, as HLS designs.

Per-construct coverage is `test_backend_symmetry.py`. This module checks the
properties only a whole chain can show: one design with no host runtime, and
C-sim of that complete design through Vitis HLS against the NumPy reference.
"""

import concurrent.futures
import re
import sys

import numpy as np
import pytest
import sar

from conftest import REPO_ROOT, requires_hls

sys.path.insert(0, str(REPO_ROOT / "benchmarks"))

from algorithms import ALL, load  # noqa: E402

pytestmark = requires_hls

#: Bounded validation geometry; chain structure is independent of raster size,
#: and PFA resamples onto twice its input.
_N = {"pfa": 32}

#: Anything that would need a host runtime on the device.
_HOST_ONLY = re.compile(r"\b(malloc|free|printf|std::cout|new|delete)\b")


@pytest.mark.parametrize("name", ALL)
def test_chain_emits_one_synthesizable_design(name):
    chain = load(name, _N.get(name, 64))
    design = chain.compile_kernel(backend="hls")
    source = design.source()

    assert f"void {design.name}(" in source, "no top function"
    assert "#pragma HLS" in source, "no directives"
    assert not _HOST_ONLY.findall(source), "host runtime in a device design"
    # One design, not a chain of them: the top function is the only entry
    # point, and everything else it calls is declared in the package header.
    header = design.header_source()
    assert header.count(f"void {design.name}(") == 1
    assert "Generated by SAR-DSL HLS artifact generation." in header
    if design.has_tables():
        tables = design.tables_source()
        assert "Generated by SAR-DSL HLS artifact generation." in tables


def test_complete_c64_chains_hls_csim_against_numpy(tmp_path, monkeypatch):
    """All four emitted imaging chains execute against the same reference."""
    from conftest import run_hls_csim

    monkeypatch.setenv("SAR_DSL_DISABLE_CACHE", "1")

    def run(name):
        chain = load(name, 32, dtype=sar.c64)
        reference = chain.run_reference()
        if isinstance(reference, (tuple, list)):
            expected = list(reference)
        else:
            expected = [reference]
        design = chain.compile_kernel(backend="hls")
        output = tmp_path / name
        peak = max(float(np.max(np.abs(plane))) for plane in expected)
        design.write_testbench(chain.args,
                               expected,
                               output,
                               rtol=1e-4,
                               atol=max(1e-7, peak * 1e-5))
        run_hls_csim(output, design.name)

    with concurrent.futures.ThreadPoolExecutor(max_workers=len(ALL)) as pool:
        futures = [pool.submit(run, name) for name in ALL]
        for future in futures:
            future.result()
