"""Locates external tools (sar-opt, mlir-translate, clang, ScaleHLS, ...).

Search order for a tool named `foo-bar`:
1. environment variable ``SAR_DSL_TOOL_FOO_BAR`` (full path);
2. directories listed by the generated ``sar._build_config`` module
   (created by the CMake build);
3. ``PATH``.
"""

from __future__ import annotations

import functools
import os
import shutil
import subprocess
from typing import List, Optional, Sequence

from ..errors import CompilationError, ToolchainError

try:  # generated by CMake; absent in a pure source checkout
    from .. import _build_config as _config
except ImportError:  # pragma: no cover
    _config = None


def _config_dirs() -> List[str]:
    dirs = []
    if _config is not None:
        dirs.append(getattr(_config, "SAR_DSL_TOOL_DIR", ""))
        dirs.append(getattr(_config, "LLVM_TOOL_DIR", ""))
    extra = os.environ.get("SAR_DSL_TOOL_PATH", "")
    dirs.extend(p for p in extra.split(os.pathsep) if p)
    return [d for d in dirs if d]


@functools.lru_cache(maxsize=None)
def find_tool(name: str, required: bool = True) -> Optional[str]:
    env_key = "SAR_DSL_TOOL_" + name.upper().replace("-", "_")
    override = os.environ.get(env_key)
    if override:
        if not os.path.isfile(override):
            raise ToolchainError(f"{env_key}={override} does not exist")
        return override

    for directory in _config_dirs():
        candidate = os.path.join(directory, name)
        if os.path.isfile(candidate) and os.access(candidate, os.X_OK):
            return candidate

    found = shutil.which(name)
    if found:
        return found

    if required:
        raise ToolchainError(
            f"required tool '{name}' not found; build the project "
            f"(see README) or set {env_key}")
    return None


@functools.lru_cache(maxsize=None)
def find_runtime_library() -> str:
    override = os.environ.get("SAR_DSL_RUNTIME_LIB")
    if override:
        if not os.path.isfile(override):
            raise ToolchainError(
                f"SAR_DSL_RUNTIME_LIB={override} does not exist")
        return override
    if _config is not None:
        candidate = getattr(_config, "SAR_DSL_RUNTIME_LIB", "")
        if candidate and os.path.isfile(candidate):
            return candidate
    raise ToolchainError(
        "libsar_runtime.so not found; build the project or set "
        "SAR_DSL_RUNTIME_LIB")


def run_tool(stage: str,
             command: Sequence[str],
             input_text: Optional[str] = None) -> str:
    """Runs a tool, returning stdout; raises CompilationError on failure."""
    proc = subprocess.run(list(command),
                          input=input_text,
                          capture_output=True,
                          text=True)
    if proc.returncode != 0:
        raise CompilationError(stage, command, proc.stderr or proc.stdout)
    return proc.stdout
